//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Companion {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ConfigFileResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConfigFileResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Companion.ConfigFileResources", typeof(ConfigFileResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [auth.anonymous]
        ///enabled = true
        ///org_name = Ficsit
        ///
        ///[security]
        ///admin_user=ficsit
        ///admin_password=pioneer.
        /// </summary>
        internal static string GranaConfiguration {
            get {
                return ResourceManager.GetString("GranaConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to global:
        ///  scrape_interval:     15s # By default, scrape targets every 15 seconds.
        ///
        ///# A scrape configuration containing exactly one endpoint to scrape:
        ///# Here it&apos;s Prometheus itself.
        ///scrape_configs:
        ///  # The job name is added as a label `job=&lt;job_name&gt;` to any timeseries scraped from this config.
        ///  - job_name: &apos;prometheus&apos;
        ///
        ///    # Override the global default and scrape targets from this job every 5 seconds.
        ///    scrape_interval: 5s
        ///
        ///    static_configs:
        ///      - targets: [&apos;localhost:9090&apos;].
        /// </summary>
        internal static string PrometheusConfiguration {
            get {
                return ResourceManager.GetString("PrometheusConfiguration", resourceCulture);
            }
        }
    }
}
