//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Companion {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Dashboards {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Dashboards() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Companion.Dashboards", typeof(Dashboards).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///&quot;dashboard&quot;: {
        ///  &quot;annotations&quot;: {
        ///    &quot;list&quot;: [
        ///      {
        ///        &quot;builtIn&quot;: 1,
        ///        &quot;datasource&quot;: &quot;-- Grafana --&quot;,
        ///        &quot;enable&quot;: true,
        ///        &quot;hide&quot;: true,
        ///        &quot;iconColor&quot;: &quot;rgba(0, 211, 255, 1)&quot;,
        ///        &quot;name&quot;: &quot;Annotations &amp; Alerts&quot;,
        ///        &quot;type&quot;: &quot;dashboard&quot;
        ///      }
        ///    ]
        ///  },
        ///  &quot;editable&quot;: true,
        ///  &quot;gnetId&quot;: null,
        ///  &quot;graphTooltip&quot;: 0,
        ///  &quot;id&quot;: null,
        ///  &quot;iteration&quot;: 1621775327334,
        ///  &quot;links&quot;: [],
        ///  &quot;panels&quot;: [
        ///    {
        ///      &quot;aliasColors&quot;: {},
        ///      &quot;bars&quot;: false,
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Power {
            get {
                return ResourceManager.GetString("Power", resourceCulture);
            }
        }
    }
}
