on: pull_request
name: Pull Request
jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ">=1.22.0"
      - name: gofmt
        working-directory: ./Companion
        run: |
          if [ "$(gofmt -l . | wc -l)" -gt 0 ]; then
            exit 1
          fi
  test:
    defaults:
      run:
        shell: powershell
    name: test
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17'

      - name: Install dependencies
        run: |
          cd Companion
          go mod vendor

      - name: Build
        shell: sh
        run: |
          cd Companion
          make

      - name: Test Companion
        run: |
          cd Companion
          make test

      - name: Test README generation
        run: |
          make readme
