on: pull_request
name: Pull Request
jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ">=1.22.0"
      - name: gofmt
        working-directory: ./Companion
        run: |
          if [ "$(gofmt -l . | wc -l)" -gt 0 ]; then
            exit 1
          fi
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ">=1.22.0"
      - name: Test Companion
        working-directory: ./Companion
        run: go test ./...
      - name: Test README generation
        working-directory: ./Companion
        run: go run main.go -GenerateReadme > ../README.md
