on: pull_request
name: Pull Request
jobs:
  test:
    name: test
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - name: Install dependencies
        run: |
          dotnet restore
          dotnet tool restore

      - name: Build
        run: |
            dotnet cake build.cake --target Build --configuration Release